services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: football-api
    ports:
      - "8002:8000"
    restart: always

  app:
    image: python:3.11-slim
    container_name: football-streamlit
    working_dir: /app
    volumes:
      - .:/app
    command: >
      sh -c "pip install --no-cache-dir -r requirements-app.txt &&
             streamlit run app/streamlit_app.py --server.port 8501 --server.address 0.0.0.0"
    ports:
      - "8501:8501"
    depends_on:
      - api